python run_ecog.py 0
python run_ecog.py 1
python run_ecog.py 2
python run_ecog.py 3
python run_ecog.py 4
python run_ecog.py 5
python run_ecog.py 6
python run_ecog.py 7
python run_ecog.py 8
python run_ecog.py 9
